"""Initial schema

Revision ID: 366b6f639637
Revises:
Create Date: 2026-02-21 23:18:30.420759

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "366b6f639637"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    _CURRENT_TS = "(CURRENT_TIMESTAMP)"
    _FK_IMAGES = "images.id"
    _FK_PERSONS = "persons.id"
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "indexed_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "embedding_clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            [_FK_PERSONS],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(), nullable=True),
        sa.Column(
            "taken_at_source",
            sa.Enum("exif", "filesystem", "manual", name="takenatsource"),
            nullable=False,
        ),
        sa.Column("camera_make", sa.String(), nullable=True),
        sa.Column("camera_model", sa.String(), nullable=True),
        sa.Column("gps_lat", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("gps_lon", sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column("gps_altitude", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            [_FK_IMAGES],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_id"),
    )
    with op.batch_alter_table("image_metadata", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_metadata_taken_at"), ["taken_at"], unique=False
        )

    op.create_table(
        "image_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("tag_key", sa.String(), nullable=False),
        sa.Column("tag_value", sa.String(), nullable=False),
        sa.Column(
            "tag_source", sa.Enum("model", "manual", name="tagsource"), nullable=False
        ),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            [_FK_IMAGES],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_id", "tag_key", "tag_source", name="uq_image_tag"),
    )
    op.create_table(
        "faces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("faiss_id", sa.Integer(), nullable=False),
        sa.Column("bbox_x", sa.Integer(), nullable=False),
        sa.Column("bbox_y", sa.Integer(), nullable=False),
        sa.Column("bbox_w", sa.Integer(), nullable=False),
        sa.Column("bbox_h", sa.Integer(), nullable=False),
        sa.Column("detection_confidence", sa.Float(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("unidentified", "identified", "anonymous", name="facestate"),
            nullable=False,
        ),
        sa.Column("labelled_at", sa.DateTime(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["embedding_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            [_FK_IMAGES],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            [_FK_PERSONS],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_faces_image_id"), ["image_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_faces_state"), ["state"], unique=False)

    op.create_table(
        "suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("face_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "confirmed", "rejected", name="suggestionstate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text(_CURRENT_TS),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["embedding_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["face_id"],
            ["faces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            [_FK_PERSONS],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suggestions")
    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_faces_state"))
        batch_op.drop_index(batch_op.f("ix_faces_image_id"))

    op.drop_table("faces")
    op.drop_table("image_tags")
    with op.batch_alter_table("image_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_metadata_taken_at"))

    op.drop_table("image_metadata")
    op.drop_table("embedding_clusters")
    op.drop_table("persons")
    op.drop_table("images")
    # ### end Alembic commands ###
