"""make file hash optional

Revision ID: 3971390d31d7
Revises: 96cc1feaa24c
Create Date: 2026-02-22 17:17:17.576258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3971390d31d7"
down_revision: Union[str, Sequence[str], None] = "96cc1feaa24c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.alter_column("file_hash", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.alter_column("file_hash", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
