"""add index on image_tags.tag_key

Revision ID: 96cc1feaa24c
Revises: 366b6f639637
Create Date: 2026-02-22 16:13:03.282252

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96cc1feaa24c"
down_revision: str | Sequence[str] | None = "366b6f639637"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_tags_tag_key"), ["tag_key"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_tags_tag_key"))

    # ### end Alembic commands ###
