name: CI + Package (main)

on:
  push:
    branches:
      - main

concurrency:
  group: main-build
  cancel-in-progress: false

jobs:
  build-and-test:
    uses: ./.github/workflows/job_ci.yml

  package:
    needs: build-and-test
    uses: ./.github/workflows/job_package.yml
