name: CI (branches + PRs)

on:
  push:
    branches:
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/job_ci.yml
